### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1015]
Hello! I just post this issue to inform you that I have today started to work on adding a German translation.
I am just giving you a heads-up, to avoid potential clashes.
I will talk back to you when I am finished.

**Comment by bobbens** [comment]
Sounds good! Note that I never really in-depth tested the translation system, although my initial tests with Japanese did show it worked. If you run into any issues, please let us know!

**Comment by Wuzzy2** [comment]
I now have translated over 50% of all strings. I can't predict when I will be finished, however.

I have not yet been able to test the translation, sadly, I don't know what I do wrong in the compilation process. I added `de` to `LINGUAS` but it didn't work.

**Comment by bobbens** [comment]
I think you have to do a "make install" to get it to work. I was trying to get the translations to actually go into the ndata and get loaded from that (with our framework), but it doesn't seem trivial.

**Comment by Wuzzy2** [comment]
Doesn't work either. My German translation does end up in `/usr/local/share/locale/de/LC_MESSAGES`, but the file name is literally “`@GETTEXT_PACKAGE@.mo`” and when I start Naev, it's still all English.
Renaming it to `naev.mo` doesn't help either.

By the way: I constantly get the warning from Gettext tools that the translatable strings should not include `\a`. I think this should be fixed, but I don't know if this is the cause for this problem.

**Comment by bobbens** [comment]
I can try to check it again to see what is wrong. I remember it was fairly clunky (like gettext in general), and I wanted to see if there was a better way of implementing it. However, it might be fairly tricky.

About '\a', that is an escape character we use for changing the font color, which gettext seems to hate, not sure if it is possible to quiet the warnings, but it should not be an issue. It might be possible to use a different character, but I did not want to write a very complicated parser. However, if we do a markdown-type solution for font boldness (#1022), then it might be able to change elegantly.

**Comment by Wuzzy2** [comment]
Replace the "\a" sequence with something else. Maybe replace backslash with something else. Dollar sign, maybe? And double dollar sign for literal dollar. This approach should (hopefully) be the least disruptive.

I'm now at 74%.

**Comment by bobbens** [comment]
It should be possible to replace it as proposed in #1029 .

Regarding the gettext stuff. I fixed it, it should now use your translation when you do "make install". The only issue is it might need a different font other than the default. Probably not for German, but Japanese just shows boxes with the default font.

**Comment by Wuzzy2** [comment]
Still doesn't work. :-(

I don't know what I do wrong. I tried resetting the repo, using a clean profile. Nothing works.

Also, I still get `@GETTEXT_PACKAGE@.mo` in `/usr/local/share/locale/...`.

**Comment by bobbens** [comment]
Did you add "de" to LINGUAS?

**Comment by Wuzzy2** [comment]
Yes. :-(

**Comment by Wuzzy2** [comment]
Good news! Today I have reached 100%! I am now in the proofreading phase and I expect to upload the result tomorrow.

**Comment by bobbens** [comment]
Sounds good!

**Comment by Wuzzy2** [comment]
PR: #1064

**Comment by Wuzzy2** [comment]
For your interest: The last translation update added a ton of new strings. I started working on translation again, but this time, it will probably take much longer to complete.
I'm at 52% right now.
