### ISSUE TITLE
Segfault when opening "Options" from the main menu

### ISSUE THREAD

**Issue by gunchleoc** [naev/naev#1117]
On current master (f8fce97b6e6920128d1f0b98d46ad40e8530ac39)
I did not get this on fa3bfcf070f1eb65318dd95f7a6359338fc07dd2 so the bug was caused somewhere in between.

```
$ gdb naev
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from naev...done.
(gdb) run
Starting program: naev 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
 Naev v0.8.0-beta1 (x86_64-pc-linux-gnu)
 git HEAD at f8fce97b6
[New Thread 0x7fffebe32700 (LWP 17275)]
BFD backtrace catching enabled.
[New Thread 0x7fffe3896700 (LWP 17276)]
 Sea of Darkness

SDL: 2.0.8 [compiled: 2.0.8]

OpenGL Window Created: 1024x768@24bpp window
r: 8, g: 8, b: 8, a: 0, db: yes, fsaa: 0, tex: 16384
vsync: no, mm: yes, compress: no, npot: no
Renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
Version: 4.5 (Core Profile) Mesa 19.2.8

Using default font '/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf'
[New Thread 0x7ffff7ef6700 (LWP 17277)]
[Thread 0x7ffff7ef6700 (LWP 17277) exited]
[New Thread 0x7fffe2d95700 (LWP 17278)]
[Thread 0x7fffe2d95700 (LWP 17278) exited]
[New Thread 0x7fffe2d95700 (LWP 17279)]
[New Thread 0x7fffe2594700 (LWP 17280)]
OpenAL started: 44100 Hz
Renderer: OpenAL Soft
Version: 1.1 ALSOFT 1.18.2 with EFX 1.0

Loaded 42 Sounds
[New Thread 0x7fffe2393700 (LWP 17281)]
Loaded 48 Songs
Loaded 16 Nebula Layers
Loaded 49 Commodities
Loaded 36 Factions
Loaded 37 AI Profiles
Loaded 119 Missions
Loaded 22 Events
Loaded 433 Outfits
Loaded 82 Ships
Loaded 134 Fleets
Loaded 63 tech groups
Loaded 373 Star Systems
       with 1141 Planets
Loaded 7 map decorators.

Thread 1 "naev" received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) backtrace
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x000055555560cce2 in opt_gameplay (wid=4) at options.c:277
#2  0x000055555560e7b6 in opt_menu () at options.c:125
#3  0x000055555564f4b3 in toolkit_mouseEventWidget (ry=<optimized out>, rx=<optimized out>, y=<optimized out>, x=<optimized out>, event=0x7fffffffbd20, wgt=0x555559737840, w=0x555559737490)
    at toolkit.c:1648
#4  toolkit_mouseEvent (event=0x7fffffffbd20, w=0x555559737490) at toolkit.c:1544
#5  toolkit_inputWindow (wdw=0x555559737490, event=event@entry=0x7fffffffbd20, purge=purge@entry=1) at toolkit.c:1444
#6  0x000055555564f5e8 in toolkit_input (event=event@entry=0x7fffffffbd20) at toolkit.c:1407
#7  0x00005555555cbefa in input_handle (event=0x7fffffffbd20) at input.c:1568
#8  0x0000555555584930 in main (argc=<optimized out>, argv=<optimized out>) at naev.c:497
(gdb) 

```

**Comment by bobbens** [comment]
Do you have a "dat/LANGUAGES"?
Likely fixed in master.

**Comment by gunchleoc** [comment]
I do, these are its contents:

```
de
ja
```

I grabbed a fresh clone and ran `./autogen.sh && ./configure && make j 11` and the crash still happens.

**Comment by onpon4** [comment]
I just did a test and I'm reproducing this. AddressSanitizer doesn't detect anything unusual.

**Comment by bobbens** [comment]
Could you print the backtrace again? Ideally run it under gdb and print the output of `bt full`

**Comment by onpon4** [comment]
Here you go: https://gist.github.com/onpon4/86524c212fdba66313c7e483a78ed828

**Comment by onpon4** [comment]
Clarification: this isn't just if it's from the main menu, I get a segfault any time the Options menu is opened.

**Comment by bobbens** [comment]
Fixed in a497c373f4f7f98121a660ed074ac63588e6d3b7 . Thanks!

**Comment by gunchleoc** [comment]
Fix confirmed :)
