### ISSUE TITLE
[Bug]: achack3: Harja does not turn up

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2471]
### What happened?

I've been flying around in Sirius space for ages and Joanne has asked twice if I still want to find Harja. I feel he is very well hidden. Check the logs in case you are interested. ;-)
[no_Harja.zip](https://github.com/naev/naev/files/13550287/no_Harja.zip)

### Version

0.11.0 beta-1+24 (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment]
Oops, should be fixed. Thanks!

**Comment by BM-W1** [comment]
REOPEN: There is still a problem in the mission: Harja turns up and can be "interviewed". He however turns up again after that and the mission text changes back to befort meeting him. Nevertheless Joanne finishes the mission. In the attached screenshot you can see this in the corner behind Joanne's backgrund.
![Screenshot_20231206_231153](https://github.com/naev/naev/assets/122737685/474e1acc-5825-4d76-86bf-6652c051e8a6)

**Comment by bobbens** [comment]
So the bug is harja spawns again after you board him, right? Sorry about that, should be fixed now!
