### ISSUE TITLE
Crash in game in za'lek areas

### ISSUE THREAD

**Issue by pisaacson** [naev/naev#493]
I have a crash that happens only in za'lek areas, specifically in the area just to the right of their territory in the pirate heavy areas. None of the rest of the map causes this crash, but I can't even explore this area as naev crashes a system or two in.

I am on OS X using an autotools build, built with external lua 5.1.5, debug mode.

I haven't figured out where the log files are at yet, as they are not in any of the listed spots. (Could logfile location be added to the debug output?)

 Naev v0.6.0
 git HEAD at naev-0.6.0-173-g95e64be
 Sea of Darkness

SDL: 2.0.3 [compiled: 2.0.3]

OpenGL Window Created: 1280x800@32bpp window
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 8192
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: NVIDIA GeForce 8600M GT OpenGL Engine
Version: 2.1 NVIDIA-10.0.31 310.90.10.05b12

OpenAL started: 1576046064 Hz
Renderer: Software
Version: 1.1 without EFX

Loaded 35 sounds
Loaded 47 songs
Loaded 16 Nebula Layers
Loaded 41 Commodities
Loaded 30 Factions
Loaded 34 AI Profiles
Loaded 85 Missions
Loaded 32 Events
Loaded 264 Outfits
Loaded 77 Ships
Loaded 111 Fleets
Loaded 59 tech groups
Loaded 373 Star Systems with 1106 Planets

Process:               naev [56943]
Path:                  /opt/local/bin/naev
Identifier:            naev
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [268]
Responsible:           Terminal [235]
User ID:               502

Date/Time:             2015-05-21 20:12:33.168 -0500
OS Version:            Mac OS X 10.10.4 (14E17e)
Report Version:        11
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   naev                            0x000000010a69c2d8 pilot_stopBeam + 27
1   naev                            0x000000010a6bafd8 weapons_updateLayer + 755
2   naev                            0x000000010a6bacd1 weapons_update + 20
3   naev                            0x000000010a66b44a update_routine + 107
4   naev                            0x000000010a66b05c main_loop + 436
5   naev                            0x000000010a66a8ab main + 2938
6   libdyld.dylib                   0x00007fff83b5c5c9 start + 1

Thread 1:: threadpool_handler
0   libsystem_kernel.dylib          0x00007fff8f775136 __psynch_cvwait + 10
1   libSDL2-2.0.0.dylib             0x000000010a7f4744 SDL_CondWaitTimeout_REAL + 141
2   libSDL2-2.0.0.dylib             0x000000010a7f439f SDL_SemWaitTimeout_REAL + 75
3   naev                            0x000000010a6b600c threadpool_handler + 266
4   libSDL2-2.0.0.dylib             0x000000010a7bb6fa SDL_RunThread + 60
5   libSDL2-2.0.0.dylib             0x000000010a7f4123 RunThread + 9
6   libsystem_pthread.dylib         0x00007fff8aee2268 _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff8aee21e5 _pthread_start + 176
8   libsystem_pthread.dylib         0x00007fff8aee041d thread_start + 13

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff8f776232 kevent64 + 10
1   libdispatch.dylib               0x00007fff90d76a6a _dispatch_mgr_thread + 52

Thread 3:
0   libsystem_kernel.dylib          0x00007fff8f7704de mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff8f76f64f mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff8fac8eb4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff8fac837b __CFRunLoopRun + 1371
4   com.apple.CoreFoundation        0x00007fff8fac7bd8 CFRunLoopRunSpecific + 296
5   com.apple.AppKit                0x00007fff8b4dd67b _NSEventThread + 137
6   libsystem_pthread.dylib         0x00007fff8aee2268 _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff8aee21e5 _pthread_start + 176
8   libsystem_pthread.dylib         0x00007fff8aee041d thread_start + 13

Thread 4:: music_thread
0   libsystem_kernel.dylib          0x00007fff8f77548a __semwait_signal + 10
1   libSDL2-2.0.0.dylib             0x000000010a7f9fc1 SDL_Delay_REAL + 84
2   naev                            0x000000010a668a5f music_thread + 82
3   libSDL2-2.0.0.dylib             0x000000010a7bb6fa SDL_RunThread + 60
4   libSDL2-2.0.0.dylib             0x000000010a7f4123 RunThread + 9
5   libsystem_pthread.dylib         0x00007fff8aee2268 _pthread_body + 131
6   libsystem_pthread.dylib         0x00007fff8aee21e5 _pthread_start + 176
7   libsystem_pthread.dylib         0x00007fff8aee041d thread_start + 13

Thread 5:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib          0x00007fff8f7704de mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff8f76f64f mach_msg + 55
2   com.apple.audio.CoreAudio       0x00007fff8a35e57e HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t_, bool, unsigned int) + 98
3   com.apple.audio.CoreAudio       0x00007fff8a35e50c HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 42
4   com.apple.audio.CoreAudio       0x00007fff8a35caa9 HALC_ProxyIOContext::IOWorkLoop() + 965
5   com.apple.audio.CoreAudio       0x00007fff8a35c612 HALC_ProxyIOContext::IOThreadEntry(void_) + 88
6   com.apple.audio.CoreAudio       0x00007fff8a35c4e3 HALB_IOThread::Entry(void*) + 157
7   libsystem_pthread.dylib         0x00007fff8aee2268 _pthread_body + 131
8   libsystem_pthread.dylib         0x00007fff8aee21e5 _pthread_start + 176
9   libsystem_pthread.dylib         0x00007fff8aee041d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib          0x00007fff8f77594a __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff8aee040d start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fb6338aa200  rbx: 0x00007fb6345435c0  rcx: 0x000000010a6bb12c  rdx: 0x00007fb630ebb4e0
  rdi: 0xd00007fb63452f6f  rsi: 0x00007fb6345435c0  rbp: 0x00007fff555e0140  rsp: 0x00007fff555e0130
   r8: 0x00007fff555dffd0   r9: 0x00007fff72b67300  r10: 0x0000000000000019  r11: 0x00000000ffffdc28
  r12: 0x000000010a6f3acc  r13: 0x00007fb634245fc0  r14: 0x0000000000000008  r15: 0x0000000000000008
  rip: 0x000000010a69c2d8  rfl: 0x0000000000210286  cr2: 0x0000000116cc9000

Logical CPU:     1
Error Code:      0x00000000
Trap Number:     13

**Comment by Deiz** [comment]
That's an issue that was fixed in 87407254 back in February, and the commit identifier in your output isn't part of our repository. It's possible that the packager's repo has diverged from ours and is missing that commit.

What you've posted is the full log from a typical run. Naev only writes its output to file when not running from a terminal.

**Comment by pisaacson** [comment]
Sorry, I was sure that I had repulled a fresh local copy, but I was still linked to bobbens/naev. Sorry for the trouble.

**Comment by pisaacson** [comment]
I am reopening this as I am still seeing this issue, as I am still seeing this with ToT. I use a local portfile with macports for the the build, so it should be a clean install every time except for the config/savegame files in my user directory

Naev v0.6.0
 git HEAD at naev-0.6.0-175-g32d8ee7
 Sea of Darkness

SDL: 2.0.3 [compiled: 2.0.3]

OpenGL Window Created: 1280x800@32bpp window
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 8192
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: NVIDIA GeForce 8600M GT OpenGL Engine
Version: 2.1 NVIDIA-10.0.31 310.90.10.05b12

OpenAL started: 1351335408 Hz
Renderer: Software
Version: 1.1 without EFX

Loaded 35 sounds
Loaded 47 songs
Loaded 16 Nebula Layers
Loaded 41 Commodities
Loaded 30 Factions
Loaded 34 AI Profiles
Loaded 85 Missions
Loaded 32 Events
Loaded 264 Outfits
Loaded 77 Ships
Loaded 111 Fleets
Loaded 59 tech groups
Loaded 373 Star Systems with 1106 Planets
iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Segmentation fault: 11

**Comment by ids1024** [comment]
Is there any chance you could use gdb to get a backtrace for this crash?

There are instructions for this in the wiki: http://wiki.naev.org/wiki/Debugging

**Comment by pisaacson** [comment]
My current build isn't a debug build, it doesn't seem look any different than the text of the crash log I posted in the first comment:


Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x000000010007a78e in pilot_stopBeam ()
#0  0x000000010007a78e in pilot_stopBeam ()
No symbol table info available.
#1  0x0000000100098688 in weapons_updateLayer ()
No symbol table info available.
#2  0x0000000100098381 in weapons_update ()
No symbol table info available.
#3  0x000000010004acd7 in update_routine ()
No symbol table info available.
#4  0x000000010004a8fa in main_loop ()
No symbol table info available.
#5  0x000000010004a149 in main ()
No symbol table info available.

I will have output from a debug build later this week.

**Comment by bobbens** [comment]
I think @Deiz fixed this at some point in time. Have to double check.

**Comment by pisaacson** [comment]
So I created a debug build from ToT (previous build was approx from end of May), and ran with gdb with the same results. I gave lldb a spin I don't know if it is more helpful or not. My simplified test run is repeatedly traveling between Bastion Station, in Pultatis and Fried until the crash triggers. It almost always takes less than a handful to trigger it. I am almost always in autonav when it occurs.

(lldb) target create "naev"
Current executable set to 'naev' (x86_64).
(lldb) run
Process 56462 launched: '/opt/local/bin/naev' (x86_64)
 Naev v0.6.0
 git HEAD at naev-0.6.0-213-gc8b8e97
 Sea of Darkness

SDL: 2.0.3 [compiled: 2.0.3]

OpenGL Window Created: 1280x800@32bpp window
r: 8, g: 8, b: 8, a: 8, db: yes, fsaa: 0, tex: 8192
vsync: no, vbo: no, mm: no, compress: no, npot: no
Renderer: NVIDIA GeForce 8600M GT OpenGL Engine
Version: 2.1 NVIDIA-10.0.32 310.90.10.05b12

OpenAL started: -1891113507 Hz
Renderer: Software
Version: 1.1 without EFX

Loaded 35 sounds
Loaded 47 songs
Loaded 16 Nebula Layers
Loaded 41 Commodities
Loaded 30 Factions
Loaded 34 AI Profiles
Loaded 85 Missions
Loaded 32 Events
Loaded 264 Outfits
Loaded 77 Ships
Loaded 111 Fleets
Loaded 59 tech groups
Loaded 373 Star Systems with 1106 Planets
iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Warning: [al_checkHandleError] OpenAL error [al_playVoice]: unknown error
Process 56462 stopped
* thread #1: tid = 0x1fed0, 0x000000010007df61 naev`pilot_stopBeam + 27, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x000000010007df61 naev`pilot_stopBeam + 27
naev`pilot_stopBeam:
->  0x10007df61 <+27>: movl   0x70(%rdi), %ecx
    0x10007df64 <+30>: cmpl   $0x3, %ecx
    0x10007df67 <+33>: jne    0x10007df7b               ; <+53>
    0x10007df69 <+35>: movsd  0x2873f(%rip), %xmm0
(lldb) thread backtrace
* thread #1: tid = 0x1fed0, 0x000000010007df61 naev`pilot_stopBeam + 27, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x000000010007df61 naev`pilot_stopBeam + 27
    frame #1: 0x000000010009cdca naev`weapons_updateLayer + 783
    frame #2: 0x000000010009caa7 naev`weapons_update + 20
    frame #3: 0x000000010004c725 naev`update_routine + 107
    frame #4: 0x000000010004c337 naev`main_loop + 441
    frame #5: 0x000000010004bb84 naev`main + 2924
    frame #6: 0x00007fff8b7265ad libdyld.dylib`start + 1
(lldb) frame select 1
frame #1: 0x000000010009cdca naev`weapons_updateLayer + 783
naev`weapons_updateLayer:
    0x10009cdca <+783>: jmp    0x10009ce2b               ; <+880>
    0x10009cdcc <+785>: callq  0x10006d6e7               ; outfit_spfxArmour
    0x10009cdd1 <+790>: cmpl   $-0x1, %eax
    0x10009cdd4 <+793>: je     0x10009ce2b               ; <+880>
(lldb) frame select 2
frame #2: 0x000000010009caa7 naev`weapons_update + 20
naev`weapons_update:
    0x10009caa7 <+20>: movl   $0x1, %edi
    0x10009caac <+25>: movsd  -0x8(%rbp), %xmm0
    0x10009cab1 <+30>: addq   $0x10, %rsp
    0x10009cab5 <+34>: popq   %rbp
(lldb) frame select 3
frame #3: 0x000000010004c725 naev`update_routine + 107
naev`update_routine:
    0x10004c725 <+107>: movsd  -0x8(%rbp), %xmm0
    0x10004c72a <+112>: callq  0x100095376               ; spfx_update
    0x10004c72f <+117>: movsd  -0x8(%rbp), %xmm0
    0x10004c734 <+122>: callq  0x100079418               ; pilots_update
(lldb) frame select 4
frame #4: 0x000000010004c337 naev`main_loop + 441
naev`main_loop:
    0x10004c337 <+441>: cmpl   %r13d, %r14d
    0x10004c33a <+444>: jge    0x10004c373               ; <+501>
    0x10004c33c <+446>: movsd  -0x48(%rbp), %xmm1
    0x10004c341 <+451>: movsd  -0x40(%rbp), %xmm2
(lldb) frame select 5
frame #5: 0x000000010004bb84 naev`main + 2924
naev`main:
    0x10004bb84 <+2924>: movzbl 0x86145(%rip), %eax       ; quit
    0x10004bb8b <+2931>: cmpl   $0x1, %eax
    0x10004bb8e <+2934>: jne    0x10004bb2b               ; <+2835>
    0x10004bb90 <+2936>: leaq   -0x830(%rbp), %rdi
(lldb) frame select 6
frame #6: 0x00007fff8b7265ad libdyld.dylib`start + 1
libdyld.dylib`start:
    0x7fff8b7265ad <+1>: movl   %eax, %edi
    0x7fff8b7265af <+3>: callq  0x7fff8b7265e0            ; symbol stub for: exit
    0x7fff8b7265b4 <+8>: hlt    
    0x7fff8b7265b5:      nop

**Comment by ids1024** [comment]
I just tracked down the original error message I got that 8740725 was supposed to fix (and did as far as I could tell, since I have not had the same problem since). There is a slight difference, in that the original segfault seemed to occur in `pilot_getRateMod` which was called by `pilot_stopBeam`, whereas this just shows `pilot_stopBeam`. I don't know if that helps at all for debugging this.

http://pastebin.com/2LfVDbus

**Comment by ids1024** [comment]
This should be fixed in https://github.com/naev/naev/commit/e3a0b5961f1fdbdbf016cd8018ff3464b7cb914a.
