### ISSUE TITLE
issue with sharkman is back mission

### ISSUE THREAD

**Issue by cfsterpka** [naev/naev#600]
In the Sharkman is Back mission after you let the shark disable and your mission status is listed as "Go to Darkshed in the Alteris system to collect your pay"  the mission is deactivated as soon as the shark jumps out of the system.

Almost forgot - I'm running naev-0.6.1-linux-x86-64 in Ubuntu

**Comment by nenau** [comment]
Hello,

I have a hypothesis : maybe someone else than the shark gave the shot that disabled you (eg a pirate). In that case, according to the script, the mission should behave exactly as you say (and it should be fixed).

Did what you described only happend once or several times ?
If you try the mission again, try to fly deep in the system in order to go away from the jump-point battle.

**Comment by cfsterpka** [comment]
I've tried the mission several times - I've even made sure that the shark was the ship that disabled me with still the same outcome.

**Comment by nenau** [comment]
I just tried the mission on current master branch : this problem did not occur.
I suppose the last commits on the shark campaign solved this.

**Comment by PhoenixRiver** [comment]
It's possible, @cfsterpka - would you be able tot try this again on the latest git version for us?

**Comment by cfsterpka** [comment]
Hmm... I've only tried once but it seems to still be happening.  I'm using the same ndata.zip, could this possibly be affecting the results?

**Comment by bobbens** [comment]
If you use the same ndata.zip, you won't get any of the new mission fixes. You have to use the newer files by either generating a new ndata.zip and using that, or use the -N or --nondata switches from the commandline to disable using the ndata.zip and use directly the git files.

**Comment by cfsterpka** [comment]
Ok, I can confirm that using the -N flag I'm able to complete the mission.  Thanks!
